### ISSUE TITLE
'A' Column not shown when it is blank

### ISSUE THREAD

**Issue by Alex-ley** [quigleyj97/jupyterlab-spreadsheet#35]
I am not sure if this is a SheetJS or SlickGrid thing, or possibly your wrapper?

But if the 'A' Column is blank it is not shown.

It's not a big deal but it is weird when you always expect an Excel sheet to show columns A through M and rows 1 to N?

The plugin is awesome btw congrats and thanks. If this is an easy fix and if it's easy for me to get my head around your code, I could potentially submit a PR.
![image](https://user-images.githubusercontent.com/39010050/117033455-aa156200-ad02-11eb-8b38-1a394e16f8f5.png)

**Comment by quigleyj97** [comment]
Oh man, thanks for reporting this! My first guess is that this is a rendering issue with SlickGrid, but the column sizes are given by SheetJS. Does this happen exclusively in sheets where all the first column cells are empty? Or is the first column resized as well? I'll see if I can repro this tonight.

**Comment by quigleyj97** [comment]
Able to reproduce this locally-

![Screen Shot 2021-07-17 at 3 51 44 PM](https://user-images.githubusercontent.com/16925819/126050979-065a6fe2-e2a2-47b8-b20a-dc697eb9234e.png)

vs the expected:

<img width="157" alt="Screen Shot 2021-07-17 at 3 52 26 PM" src="https://user-images.githubusercontent.com/16925819/126050994-c9f19843-5877-4386-bc1a-fa897db8a967.png">

Oddly, the contents of the "A" column are rendered as the "B" column, and inspecting the DOM the "A" column is straight up not present (suggesting an issue in the Model translating between SheetJS and SlickGrid's viewmodels). Investigating further

**Comment by quigleyj97** [comment]
In my test sheet, it looks like SheetJS is trying to be clever and returning a range not inclusive of the first cell/column:

https://github.com/quigleyj97/jupyterlab-spreadsheet/blob/main/src/model.ts#L94

Most of the GridWidget assumes that the letter column names and column indicies are interchangable, which would be why the expected "B" column data is missing.

Easiest fix is to update [`SpreadsheetModel#getColumnConfig()`](https://github.com/quigleyj97/jupyterlab-spreadsheet/blob/main/src/model.ts#L179) to always start from the 0th column, instead of the start of the sheet range.
